### ISSUE TITLE
Find the Best Colors for the Cubes

### ISSUE THREAD

**Issue by rlwprog** [gbroques/cozmo-song-match#17]
Not all colors are created equal.
Some colors show up better than others when displayed on the cubes. 
The colors that appear the brightest should be chosen to properly visually represent each note.
If possible, Red and Green should be excluded since they'll be reserved for representing the events associated with winning and losing. 

Colors' brightness can be properly assessed by creating an RGB loop that shows every possible color variation for the cubes.

**Comment by gbroques** [comment]
@kb5 Said Purple seems to be a promising color.
