### ISSUE TITLE
Song Match Takes Too Long

### ISSUE THREAD

**Issue by gbroques** [gbroques/cozmo-song-match#21]
Currently *Mary had a little lamb* has  25 notes. Starting with 3 notes, and incrementing by 1 note each round takes forever.

We have a few ideas on how to improve this:

*  Increment by more than 1 note each round
    * This could make the game too difficult
* After a certain threshold, end the game and play the whole song
    * For example, after 10 notes of Mary had a little lamb, end the game and play the whole song.
* Shorten the songs
    * Have songs that are shorter like 10 - 15 notes in length. Play only the most memorable part.

Per @bpowe1991 comment:

* Increase the number of notes we increment by as the song progresses
    * For example. start by incrementing by 1 note, then 1/3 of the way through the song, increment by 2 notes, then 2/3 of the way through increment by 3 notes.

**Comment by bpowe1991** [comment]
As the song progresses, increase the number of added notes per round

**Comment by gbroques** [comment]
Our solution should not require difficulty and be simple.
