### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by gbroques** [gbroques/cozmo-song-match#40]
Several things need to be updated on the documentation site:

* ~~Add information to introduction~~
    * Possibly add our game flow diagram to it.
* ~~Change **API** to **Song Match API**~~
* ~~Add Troubleshooting page~~
* ~~Add "Future Plans" / "Moving Forward" page.~~
* ~~Add Virtual Environments page and mention it in **Setup**~~
* ~~Add "Codebase Conventions" page explaining some of the common conventions and design patterns found within the codebase.~~
* ~~Add **Dependencies** page~~
* ~~Mention how to find usages of functions within PyCharm~~
* ~~Add page about package structure, and give overview of project~~
* ~~Add page about how our documentation is built and setup~~

**TROUBLESHOOTING PAGE**
~~Mention replacing the batteries on the cube if you notice flickering or other weird behavior.~~

Probably more stuff I'm not thinking of.

@kb5 @bpowe1991 @rlwprog  Any suggestions?

**Comment by kb5** [comment]
He was wanting two different flowcharts included in this documentation. We can include the flowchart that we have in the user guide for the game flow. He also is looking for a program flowchart that would show calls to functions and such.

**Comment by gbroques** [comment]
I have a branch for this up called:
[improve-documentation](https://github.com/gbroques/cozmo-song-match/tree/improve-documentation)

So far I've:
* Added more information to the introduction
* Changed API to Song Match API
* Added a page about virtual environments and updated the Setup page accordingly

**Comment by gbroques** [comment]
* Added page about dependencies

**Comment by gbroques** [comment]
* Added page about package structure

**Comment by kb5** [comment]
A troubleshooting and moving forward page was added. I mentioned the batteries on the troubleshooting page.
