### ISSUE TITLE
Randomly Select a Song upon Starting the Game

### ISSUE THREAD

**Issue by gbroques** [gbroques/cozmo-song-match#42]
Now that we have three songs, we need to randomly select one at the start of the game.

This issue depends upon issue #26.

**Comment by gbroques** [comment]
One idea was to have the game continue for multiple songs.

This was mainly because the player may have to restart the game several times to get a particular song they want to play.

I feel this is part of a larger issue, name **we don't have a great way to configure options** like which song to play.

**Comment by rlwprog** [comment]
I agree, back to the GUI issue. I think the best option would be to randomly select which song and then  continue to the other two would be the best option. Also it doesn't necessarily have to be random. It could just cycle through the songs using the same order every time.
