### ISSUE TITLE
Support multiple players

### ISSUE THREAD

**Issue by rlwprog** [gbroques/cozmo-song-match#43]
As it stands, the user interface for each round, the game ending and checking who won only support either Cozmo and a single player. 

If more than one player is playing with Cozmo, it will be hard to tell whose turn it is during each round.

If a player reaches three strikes during the game, that doesn't necessarily mean the game is over. This player should be skipped next round. 

Checking who won as well as the subsequent reactions from Cozmo need to reflect how many strikes each person (and Cozmo) have when the game is finished.

**Comment by gbroques** [comment]
Closed.
See commits 6a0de4f7 and 587644cf
